nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']  # Permite todos los orígenes (sólo para desarrollo)
        allow_methods: ['*']
        allow_headers: ['*']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': null